# Generated by Django 4.2.2 on 2023-09-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejewelleryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='c_registermodel',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='c_registermodel',
            name='pincode',
            field=models.CharField(max_length=7),
        ),
    ]
