# Generated by Django 4.2.2 on 2023-09-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejewelleryapp', '0002_admin_registermodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_registermodel',
            old_name='name',
            new_name='username',
        ),
    ]
